name: test trigger
description: "Test trigger for Kunimasu"

inputs:
  kunimasu-url:
    required: true
    description: "kunimasu url"
  repo-name:
    required: true
    description: "Repo name"
  repo-owner:
    required: true
    description: "Repo owner"
  repo-head-sha:
    required: true
    description: "Repo head sha"
  github-token:
    required: true
    description: "Github token"
outputs:
  result:
    description: "Kunimasu result"

runs:
  using: docker
  image: Dockerfile
  env:
    KUNIMASU_URL: ${{ inputs.kunimasu-url }}
    REPO_NAME: ${{ inputs.repo-name }}
    REPO_OWNER: ${{ inputs.repo-owner }}
    REPO_HEAD_SHA: ${{ inputs.repo-head-sha }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GITHUB_API_URL: ${{ github.api_url }}
    REPO: ${{ github.repository }}