name: test trigger
description: "Test trigger for Kunimasu"

inputs:
  token:
    required: true
    description: app token
  api-url:
    description: api url
    default: https://asia-northeast1-android-virtual-terminal-dev.cloudfunctions.net/__name__/v1
  app-artifact-path:
    description: app path
  workflow-run-id:
    description: workflow run Id
    default: ${{ github.run_id }}
  head-sha:
    description: The head sha
    default: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha }}
  branch:
    description: test branch
    default: ${{ (github.event_name == 'pull_request' && github.head_ref) || github.ref_name }}
  github-api-url:
    description: The API URL of the GitHub server.
    default: ${{ github.api_url }}
  repository:
    description: The full name of the repository for which the token will be requested.
    default: ${{ github.repository }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        pip install --upgrade pip
        pip install -r $GITHUB_ACTION_PATH/requirements.txt
      name: Setup Python
      shell: bash
      working-directory: .kunimasu/${{ inputs.branch }}
    - run: |
        token=${{ inputs.token }}
        api_url=${{ inputs.api-url }}
        workflow_run_id=${{ inputs.workflow-run-id }}
        file_type=apk
        
        test_trigger_url=${api_url/__name__/githubTestTrigger}/$token
        storage_access_token_url=${api_url/__name__/githubStorageAccessToken}/$token
        app_artifact_full_path=$GITHUB_WORKSPACE/${{ inputs.app-artifact-path }}
        
        echo $test_trigger_url
        echo $storage_access_token_url
        
        app_storage_url_resp=(`curl -s -X POST $storage_access_token_url -F 'file_type="'"$file_type"'"' -F 'workflow_run_id="'"$workflow_run_id"'"' -w " %{http_code}"`)
        app_storage_url=${app_storage_url_resp[0]}
        app_storage_url_status=${app_storage_url_resp[1]}
        
        echo $app_storage_url_resp
        echo $app_storage_url
        echo $app_storage_url_status
        
        if [ $app_storage_url_status != 200 ]; then
          echo Failed to upload apk. Response status code: $app_storage_url_status
          exit 1
        fi
        curl -s -X PUT -H 'Content-Type: application/vnd.android.package-archive' --data-binary @$app_artifact_full_path $app_storage_url
        
        test_plans=`python3 $GITHUB_ACTION_PATH/src/main.py ./runners`
        
        curl -s -X POST $test_trigger_url \
          -F 'branch=${{ inputs.branch }}' \
          -F 'head_sha=${{ inputs.head-sha }}' \
          -F 'github_api_url=${{ inputs.github-api-url }}' \
          -F 'repository=${{ inputs.repository }}' \
          -F 'workflow_run_id="'"$workflow_run_id"'"' \
          -F 'test_plans="'"$test_plans"'"'
      name: Trigger to system
      shell: bash
      working-directory: .kunimasu/${{ inputs.branch }}