name: test trigger
description: "Test trigger for Kunimasu"

inputs:
  api-url:
    required: true
    description: api url
  app-artifact-path:
    required: true
    description: app path
  workflow-run-id:
    description: workflow run Id
    default: ${{ github.run_id }}
  head-sha:
    description: The head sha
    default: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha }}
  branch:
    description: test branch
    default: ${{ (github.event_name == 'pull_request' && github.head_ref) || github.ref_name }}
  github-api-url:
    description: The API URL of the GitHub server.
    default: ${{ github.api_url }}
  repository:
    description: The full name of the repository for which the token will be requested.
    default: ${{ github.repository }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        
        pip install --upgrade pip
        pip install -r $GITHUB_ACTION_PATH/requirements.txt
        
        workflow_run_id=${{ inputs.workflow-run-id }}
        api_url=${{ inputs.api-url }}
        test_trigger_url=${api_url/\{api_name\}/githubTestTrigger}
        storage_access_token_url=${api_url/\{api_name\}/githubStorageAccessToken}        
        app_artifact_full_path=$GITHUB_WORKSPACE/${{ inputs.app-artifact-path }}        
        
        app_storage_url=(`curl -X POST $storage_access_token_url -F 'workflow_run_id="'"$workflow_run_id"'"'`)
        curl -X PUT -H 'Content-Type: application/vnd.android.package-archive' --data-binary @$app_artifact_full_path $app_storage_url
        
        test_plans=`python3 $GITHUB_ACTION_PATH/src/main.py ./runners`
        echo $test_plans
        
        curl -X POST $test_trigger_url \
          -F 'head_sha=${{ inputs.head-sha }}' \
          -F 'github_api_url=${{ inputs.github-api-url }}' \
          -F 'repository=${{ inputs.repository }}' \
          -F 'workflow_run_id="'"$workflow_run_id"'"' \
          -F 'test_plans="'"$test_plans"'"'
      shell: bash
      working-directory: .kunimasu/${{ inputs.branch }}