name: test trigger
description: "Test trigger for Kunimasu"

inputs:
  kunimasu-url:
    required: true
    description: "kunimasu url"
  head-sha:
    required: true
    description: "Repo head sha"
  branch:
    description: test branch
    default: ${{ (github.event_name == 'pull_request' && github.head_ref) || github.ref_name }}
  github_api_url:
    description: The API URL of the GitHub server.
    default: ${{ github.api_url }}
  repository:
    description: The full name of the repository for which the token will be requested.
    default: ${{ github.repository }}

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Change dir to kunimasu root
      run: cd .kunimasu/${{ inputs.branch }}
      shell: bash
    - name: ls
      run: ls -la
      shell: bash
    - name: Setup yarn
      run: |
        yarn install
        yarn build
        node dist/bundle.js
      shell: bash

#    - name: chmod
#     run: chmod +x $GITHUB_ACTION_PATH/script.sh
#      shell: bash
#    - name: call script
#      run: $GITHUB_ACTION_PATH/script.sh
#      shell: bash

#runs:
#  using: docker
#  image: Dockerfile
#  env:
#    KUNIMASU_URL: ${{ inputs.kunimasu-url }}
#    HEAD_SHA: ${{ inputs.head-sha }}
#    GITHUB_API_URL: ${{ inputs.github_api_url }}
#    REPOSITORY: ${{ inputs.repository }}
