name: test trigger
description: "Test trigger for Kunimasu"

inputs:
  api-url:
    required: true
    description: api url
  app-artifact-name:
    required: true
    description: app name
  workflow-run-id:
    description: workflow run Id
    default: ${{ github.run_id }}
  head-sha:
    description: The head sha
    default: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha }}
  branch:
    description: test branch
    default: ${{ (github.event_name == 'pull_request' && github.head_ref) || github.ref_name }}
  github-api-url:
    description: The API URL of the GitHub server.
    default: ${{ github.api_url }}
  repository:
    description: The full name of the repository for which the token will be requested.
    default: ${{ github.repository }}

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: |
        yarn install
        yarn build
      shell: bash
      working-directory: .kunimasu/${{ inputs.branch }}
    - name: Upload bundle file
      uses: actions/upload-artifact@v3
      with:
        name: bundle
        path: dist/bundle.js
    - run: |
        target_device_list=`node dist/bundle.js targetDeviceList`
        echo $target_device_list
        sdk_version=`node dist/bundle.js sdkVersion`
        bundle_hash_components=(`sha256sum dist/bundle.js`)
        bundle_hash=${bundle_hash_components[0]}
        echo $bundle_hash
        app_hash=9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
        curl -X POST -F file1=@dist/bundle.js ${{ inputs.api-url }} -F 'head_sha=${{ inputs.head-sha }}' \
          -F 'github_api_url=${{ inputs.github-api-url }}' -F 'repository=${{ inputs.repository }}' \
          -F 'app_artifact_name=${{ inputs.app-artifact-name }}' -F 'workflow_run_id=${{ inputs.workflow-run-id }}' \
          -F 'target_device_list="'"$target_device_list"'"' -F 'sdk_version="'"$sdk_version"'"' \
          -F 'bundle_hash="'"$bundle_hash"'"' -F 'app_hash="'"$app_hash"'"'
      shell: bash
      working-directory: .kunimasu/${{ inputs.branch }}

#    - name: chmod
#     run: chmod +x $GITHUB_ACTION_PATH/script.sh
#      shell: bash
#    - name: call script
#      run: $GITHUB_ACTION_PATH/script.sh
#      shell: bash

#runs:
#  using: docker
#  image: Dockerfile
#  env:
#    KUNIMASU_URL: ${{ inputs.kunimasu-url }}
#    HEAD_SHA: ${{ inputs.head-sha }}
#    GITHUB_API_URL: ${{ inputs.github-api-url }}
#    REPOSITORY: ${{ inputs.repository }}
