name: test trigger
description: "Test trigger for Kunimasu"

inputs:
  kunimasu-url:
    required: true
    description: "kunimasu url"
  head-sha:
    required: true
    description: "Repo head sha"
  github_api_url:
    description: The API URL of the GitHub server.
    default: ${{ github.api_url }}
  repository:
    description: The full name of the repository for which the token will be requested.
    default: ${{ github.repository }}

runs:
  using: composite
  steps:
    - name: pwd
      run: pwd
      shell: bash
    - name: call script
      run: $GITHUB_ACTION_PATH/script.sh
      shell: bash

#runs:
#  using: docker
#  image: Dockerfile
#  env:
#    KUNIMASU_URL: ${{ inputs.kunimasu-url }}
#    HEAD_SHA: ${{ inputs.head-sha }}
#    GITHUB_API_URL: ${{ inputs.github_api_url }}
#    REPOSITORY: ${{ inputs.repository }}
